name: face_attend
channels:
  - conda-forge
  - defaults
dependencies:
  # Core interpreter
  - python=3.8

  # Numeric and data stack
  - numpy=1.22.*
  - pandas=2.0.*

  # OpenCV (conda build with Win32/Qt handled by conda)
  - opencv=4.8.*

  # dlib from conda-forge (prebuilt, avoids manual build headaches)
  - dlib=19.24.*

  # Utilities
  - pip
  - setuptools
  - wheel

  # Optional: helpful system libs for image I/O (OpenCV links its own, but these help in some cases)
  - libpng
  - jpeg
  - zlib

  # Install face_recognition via pip AFTER dlib is present
  - pip:
      - face_recognition==1.3.0
